### ISSUE TITLE
TestGenerator.RandomPlans - Object reference error

### ISSUE THREAD

**Issue by SJMakin** [abb-iss/Randoop.NET#1]
Hi, 

First off let me thank you for updating this project.  I plan to use it extensively on some legacy code which I have inherited recently.

I have found an issue in the TestGenerator.RandomPlans method which I have addressed.

Line 801:
    `if (typeDesired.IsArray || typeDesired.Equals(typeof(ArrayList)) || typeDesired.FullName.Contains("System.Collections.Generic.List")) `
Should be replaced with:
    `if (typeDesired.IsArray || typeDesired.Equals(typeof(ArrayList)) || (!string.IsNullOrEmpty(typeDesired.FullName) && typeDesired.FullName.Contains("System.Collections.Generic.List")) )`

as typeDesired.FullName may be null.  

the MSDN page seems to be broken right now but here is a cache
http://webcache.googleusercontent.com/search?q=cache:mOngS1Hkj9MJ:https://msdn.microsoft.com/en-us/library/system.type.fullname%28v%3Dvs.100%29.aspx+&cd=1&hl=en&ct=clnk&gl=uk

**Comment by qxshower** [comment]
Good catch! Could you please create a pull request? Thanks!
