### ISSUE TITLE
VS2015 Extension 

### ISSUE THREAD

**Issue by SJMakin** [abb-iss/Randoop.NET#3]
I am planning on updating the extension to be a VS2015 compatible VSIX package and am creating this issue as an enhancement request, in anticipation of the pull request, in case anyone has any queries/issues.

**Comment by qxshower** [comment]
Sounds like a good plan.

**Comment by SJMakin** [comment]
OK - Got it working with VSIX.  Less painful than I expected.  Testing now.  

Could do with abstracting the common stuff between the vs2010 and vs2015 extensions in to a new library, so it is easier to maintain, as there is a lot of duplication.  :relaxed:

**Comment by SJMakin** [comment]
Hey, I updated the pull - is it OK now?

**Comment by qxshower** [comment]
I am testing it. Will merge it soon if there is no problem.

**Comment by qxshower** [comment]
I have tested it on VS2015 and it basically worked. Thanks for making this effort! 

But there are a couple of issues to be fix before I can merge it into the master branch:
1. [feature] The description of the extension should be changed to something like "an automated unit test generation tool for .NET" (a screenshot is attached)
![randoopnet-vs2015-description](https://cloud.githubusercontent.com/assets/1516884/9308350/8009570e-44d1-11e5-8ace-c862c387042d.PNG)
2. [feature] A simple user manual may be included to describe how to install the extension and how to use the tool
3. [feature] Make the .vsix compatible with VS2012, VS2013, VS2014.
4. [bug] When the "RandoopTestPrj" is removed from the Solution Explorer but remains in the project folder, an error occurs when the tool tries to create the testing project --- this may also be a bug for VS2010. (a screenshot is attached)
![randoopnet-vs2015-fail-to-create-project](https://cloud.githubusercontent.com/assets/1516884/9308354/87e1a576-44d1-11e5-8e24-150d81470e3d.PNG)

**Comment by qxshower** [comment]
Also, I totally agree that "Could do with abstracting the common stuff between the vs2010 and vs2015 extensions in to a new library, so it is easier to maintain, as there is a lot of duplication." 
--- once the problems mentioned above are fixed, we can create a new issue for this. 

Thanks!

**Comment by SJMakin** [comment]
Thanks for reviewing it.  I will take a look at those issues soon. They shouldn't bee too hard to address.

**Comment by SJMakin** [comment]
Hi - I have resolved some of the issues (1 & 3).  I have also fixed the issue with running the extension without a solution loaded.  

I am working on some documentation but want to get the coding out of the way first.  

I think number 4 will have been an issue in 2010 too, as the objects havent changed much.  It looks easy enough to resolve.  The error comes from ``` curSolution.AddFromTemplate(csTemplatePath, testPrjPath, prjName, false); ```, when ``` csTemplatePath ``` already exists.  Would you rather I prompt or just overwrite without asking?

**Comment by SJMakin** [comment]
Following what was already being done I have not added a warning when removing the directory when trying to create a new project.  It silently deletes it.  Issue 4 with this resolved!

**Comment by qxshower** [comment]
@SJMakin, before directly delete the project folder, "Directory.Delete(testPrjPath);" (as committed in the "update"), you may want to check if the testPrjPath exists, otherwise it may invoke "DirectoryNotFoundException".

**Comment by ancgate** [comment]
Is this working now in Visual Studio 2015 as a plugin? The ticket is still open!

**Comment by qxshower** [comment]
@ancgate thank you for your interest. I will close the issue and feel free to use/test it. :)
